import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import './globals.css';

export const metadata: Metadata = {
  title: 'SIBANDES',
  description: 'Generated by create next app'
};

type RootLayout = Readonly<{
  children: React.ReactNode;
}>;

export default async function RootLayout({ children }: RootLayout) {
  const cookieStore = await cookies();
  const users = cookieStore.get('users');

  return (
    <html lang='en'>
      <title>Community Service</title>
      <body className='antialiased'>{children}</body>
    </html>
  );
}
